# this config file is adapted from the one used by Pangeo:
# https://github.com/pangeo-data/pangeo-docker-images/blob/master/base-image/dask_config.yml

distributed:
  dashboard:
    link: "{JUPYTERHUB_SERVICE_PREFIX}proxy/{port}/status"

  admin:
    tick:
      limit: 5s

  scheduler:
    idle-timeout: 21600s # matches the 6 hour idle timeout from the helm chart (not sure if these are controlling the same thing)

logging:
  distributed: warning
  bokeh: critical
  # http://stackoverflow.com/questions/21234772/python-tornado-disable-logging-to-stderr
  tornado: critical
  tornado.application: error

# the below section gives defaults for launching clusters from the dask
# labextension viewer. For now, we are leaving it as the default, which starts a 
# LocalCluster object. This is b/c there are too many possible configs for a potential
# dask gateway cluster that you might want. It's better to do this programmatically
# then using the labextension UI

# labextension:
#   factory:
#     module: dask_gateway
#     class: GatewayCluster
#     args: []
#     kwargs: {}
