name: base
channels:
  - conda-forge
dependencies:
  - coverage=4.5.4
  - dask-labextension=1.0.3
  - flake8=3.7.8
  - graphviz=2.40.1
  - ipdb=0.12.2
  - ipywidgets=7.5.1
  - nano=2.9.8
  - nbconvert=5.6.0
  - nodejs=12.11.1
  - nose=1.3.7
  - openssh=7.9pl
  - pytest=5.2.1
  - pytest-cov=2.8.1
  - pytest-runner=5.1
  - sphinx=2.2.0
  - tox=3.14.0
  - tqdm=4.36.1
  - vim=8.1.1343
  - wheel=0.33.6
