name: base
channels:
  - conda-forge
dependencies:
  - coverage
  - dask-labextension
  - flake8
  - graphviz
  - ipywidgets
  - nbconvert
  - nodejs
  - nose
  - jupyterhub
  - jupyterlab
  - pytest
  - pytest-cov
  - pytest-runner
  - sphinx
  - widgetsnbextension
