name: r
channels:
  - conda-forge
  - r
dependencies:
  - rpy2=3.1.0
  - r-base=3.6.1
  - r-irkernel=1.0.2
  - r-plyr=1.8.4
  - r-devtools=2.2.1
  - r-tidyverse=1.2.1
  - r-shiny=1.3.2
  - r-rmarkdown=1.16
  - r-forecast=8.9
  - r-rsqlite=2.1.2
  - r-reshape2=1.4.3
  - r-nycflights13=1.0.1
  - r-caret=6.0_84
  - r-rcurl=1.95_4.12
  - r-crayon=1.3.4
  - r-randomforest=4.6_14
  - r-sparklyr=1.0.3
  - r-htmlwidgets=1.5
  - r-hexbin=1.27.3
