name: base
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.8.0
  - bokeh=1.3.4
  - bqplot=0.11.8
  - cartopy=0.17.0
  - click
  - cloudpickle=1.2.2
  - cytoolz=0.10.0
  - dask-core=2.4.0
  - dask-glm=0.2.0
  - dask-ml=1.0.0
  - dask=2.4.0
  - datashader=0.7.0
  - distributed=2.4.0
  - esmf=7.1.0
  - esmpy=7.1.0
  - fastparquet=0.3.2
  - fiona=1.8.6
  - fusepy
  - gcsfs=0.3.0
  - gdal=2.4.2
  - geoalchemy2=0.6.3
  - geopandas=0.5.1
  - geopy=1.20.0
  - geotiff=1.5.1
  - geoviews=1.6.3
  - git=2.23.0
  - gitpython=3.0.2
  - holoviews=1.12.5
  - ipdb=0.12.2
  - ipython=7.8.0
  - ipyleaflet=0.11.2
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jupyter_client=5.3.3
  - jupyter=1.0.0
  - jupyterhub=1.0.0
  - jupyterlab=1.1.4
  - jupyter-server-proxy
  - lz4=2.2.1
  - matplotlib=3.1.1
  - nb_conda_kernels=2.2
  - nbconvert=5.6.0
  - ncurses
  - netcdf-fortran
  - netcdf4=1.5.1.2
  - nodejs
  - nose
  - notebook=6.0.1
  - numba=0.45.1
  - numcodecs=0.6.3
  - numpy
  - pandas
  - pip
  - plotly
  - pyshp=2.1.0
  - python-blosc=1.8.1
  - python-snappy=0.5.4
  - pyviz_comms=0.7.2
  - PyYAML
  - rasterio=1.0.28
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - shapely=1.6.4
  - statsmodels=0.10.1
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.36.1
  - urllib3=1.25.6
  - widgetsnbextension=3
  - xarray=0.13.0
  - zarr=2.3.2
  - zeromq=4.3.2
  - zict=1.0.0
  - pip:
    - bumpversion
    - coverage
    - dask-labextension
    - dask-kubernetes==0.9.2
    - flake8
    - google-api-core
    - google-cloud
    - google-cloud-container
    - google-cloud-storage
    - kubernetes
    - mapbox
    - py-noaa
    - pytest
    - pytest-cov
    - pytest-runner
    - sidecar
    - Sphinx
    - tox
    - wget
    - wheel
    - xesmf
    - xlrd
