name: base
channels:
  - conda-forge
dependencies:
  - black
  - bump2version
  - coverage
  - dask-labextension
  - flake8
  - ipdb
  - ipyleaflet
  - ipympl
  - ipypublish
  - isort
  - jupyterhub=1.0.0  # pinkeep: jupyterhub=1.0.0
  - jupyterlab_code_formatter
  - nano
  - nbdime
  - nb_conda_kernels
  - octave_kernel=0.32.0=pyh9f0ad1d_0
  - oct2py=5.0.4=py_0
  - openssh
  - papermill
  - pip
  - pytest
  - pytest-cov
  - pytest-runner
  - python-graphviz
  - sidecar
  - sphinx_rtd_theme
  - tox
  - pip:
    - black_nbconvert