name: base
channels:
  - conda-forge
dependencies:
  - black
  - bump2version
  - coverage
  - dask-labextension
  - flake8
  - gitpython
  - ipdb
  - ipyleaflet
  - ipympl
  - ipypublish
  # pinning isort and jupyterlab_code_formatter until there's a version of the latter
  # on conda-forget that can support v5 of the former
  - isort=4
  - jupyterlab_code_formatter=1.3.1
  - nano
  - nb_conda_kernels
  - octave_kernel=0.32.0=pyh9f0ad1d_0
  - oct2py=5.0.4=py_0
  - openssh
  - pip
  - pytest
  - pytest-cov
  - pytest-runner
  - python-graphviz
  - sidecar
  - sphinx_rtd_theme
  - tox
  - pip:
    - black_nbconvert
