name: base
channels:
  - conda-forge
dependencies:
  - black
  - coverage
  - dask-labextension
  - flake8
  - ipdb
  - ipyleaflet
  - ipympl
  - jupyterlab_code_formatter
  - nano
  - nb_conda_kernels
  - nose
  - octave_kernel
  - oct2py
  - openssh
  - pytest
  - pytest-cov
  - pytest-runner
  - python-graphviz
  - sphinx
  - tox
  - pip:
    - black_nbconvert
