name: base
channels:
  - conda-forge
dependencies:
  - black
  - bump2version
  - coverage
  - dask-labextension
  - flake8
  - ipdb
  - ipyleaflet
  - ipympl
  - ipypublish
  - isort
# need jupyterhub version to match that running on the hub
  - jupyterhub=1.0.0 # pinkeep: jupyterhub=1.0.0
  - jupyterlab
  - jupyterlab_code_formatter
  - mypy
  - nano
  - nbdime
  - nb_conda_kernels
  - octave_kernel=0.32.0=pyh9f0ad1d_0
  - oct2py=5.2.0=pyh9f0ad1d_0
  - openssh
  - papermill
  - pip
  - pytest
  - pytest-cov
  - python-graphviz
  - sidecar
  - sphinx_rtd_theme
  - tox
  - pip:
    - black_nbconvert
    # need to clone from repo until version > 1.1.0 to fix setup.py bug
    # (https://github.com/elyra-ai/elyra/commit/2ad2e66ca1ba26c99d39f1d2eea21bd508ce6cdb)
    - git+https://github.com/elyra-ai/elyra.git@2ad2e66ca1ba26c99d39f1d2eea21bd508ce6cdb#egg=elyra
