name: base
channels:
  - conda-forge
dependencies:
  - black
  - bump2version
  - coverage
  - dask-labextension
  - flake8
  - ipdb
  - ipyleaflet
  - ipympl
  - ipypublish
  - isort
# need jupyterhub version to match that running on the hub
  - jupyterhub=1.1.0 # pinkeep: jupyterhub=1.1.0
  - jupyterlab
  - jupyterlab-git
  - jupyterlab_code_formatter
  - jupyterlab-git
  - mypy
  - nano
  - nbdime
  - nb_conda_kernels
  - octave_kernel=0.31.0=py_0
  - oct2py=5.0.4=py_0
  - openssh
  - papermill
  - pip
  - pytest
  - pytest-cov
  - python-graphviz
  - sidecar
  - sphinx_rtd_theme
  - tox
  - pip:
    - black_nbconvert
