name: base
channels:
  - conda-forge
dependencies:
  - black
  - bump2version
  - coverage
  - dask-labextension
  - elyra
  - flake8
  - gh
  - ipdb
  - ipyleaflet
  - ipympl
  - ipypublish
  - isort
# need jupyterhub version to match that running on the hub
  - jupyterhub=1.2.1 # pinkeep: jupyterhub=1.2.1
  - jupyterlab
  - jupyterlab-git
  - jupyterlab_code_formatter
  - jupyterlab-git
  - mypy
  - nano
  - nbdime
  - nb_conda_kernels
  - octave_kernel=0.32.0=pyh9f0ad1d_0
  - oct2py=5.2.0=pyh9f0ad1d_0
  - openssh
  - papermill
  - pip
  - pytest
  - pytest-cov
  - python-graphviz
  - rsync
  - sidecar
  - sphinx_rtd_theme
  - tox
  - pip:
    - black_nbconvert
