name: base
channels:
  - conda-forge
dependencies:
  - black
  - bump2version
  - coverage
  - dask-labextension
  - flake8
  - gitpython
  - ipdb
  - ipyleaflet
  - ipympl
  - isort
  - jupyterlab_code_formatter=1.3.1
  - nano
  - nb_conda_kernels
  - octave_kernel=0.32.0=pyh9f0ad1d_0
  - oct2py=5.0.4=py_0
  - openssh
  - pip
  - pytest
  - pytest-cov
  - pytest-runner
  - python-graphviz
  - sidecar
  - sphinx
  - tox
  - pip:
    - black_nbconvert
