name: worker
channels:
  - conda-forge
dependencies:
  - octave=4.2.1
  - octave_kernel=0.31.0
  - portaudio=19.6.0
  - click
  - cloudpickle=1.2.2
  - cytoolz=0.10.0
  - dask-core=2.4.0
  - dask-glm=0.2.0
  - dask-ml=1.0.0
  - dask=2.4.0
  - distributed=2.4.0
  - fastparquet=0.3.2
  - fusepy
  - gcsfs=0.3.0
  - icu=64.2
  - ipdb=0.12.2
  - ipython=7.8.0
  - jedi=0.15.1
  - jupyter_client=5.3.3
  - jupyter=1.0.0
  - lz4=2.2.1
  - matplotlib=3.1.1
  - nb_conda_kernels=2.2
  - ncurses
  - netcdf-fortran
  - netcdf4=1.5.1.2
  - nose
  - numba=0.45.1
  - numcodecs=0.6.3
  - numpy
  - pandas
  - pip
  - python-blosc=1.8.1
  - python-snappy=0.5.4
  - PyYAML
  - rasterio=1.0.28
  - scipy=1.3.1
  - statsmodels=0.10.1
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.36.1
  - urllib3=1.25.6
  - xarray=0.13.0
  - zarr=2.3.2
  - zeromq=4.3.2
  - zict=1.0.0
  - pip:
    - dask-kubernetes==0.9.2
    - google-api-core
    - google-cloud
    - google-cloud-container
    - google-cloud-storage
    - kubernetes
    - wget
    - wheel
    - xlrd
