name: base
channels:
  - conda-forge
  - conda-forge/label/dev
dependencies:
  - beautifulsoup4=4.8.0
  - boto3=1.9.243
  - bqplot=0.11.8
  - bumpversion=0.5.3
  - cachecontrol=0.12.5
  - cartopy=0.17.0
  - click=7.0
  - c-compiler=1.0.4
  - dask=2.5.2
  - dask-glm=0.2.0
  - dask-kubernetes=0.9.2
  - dask-ml=1.0.0
  - datashader=0.7.0
  - distributed=2.5.2
  - esmpy=7.1.0
  - fastparquet=0.3.2
  - fiona=1.8.7
  - fortran-compiler=1.0.4
  - fusepy=3.0.1
  - gcsfs=0.3.1
  - gdal=2.4.2
  - geoalchemy2=0.6.3
  - geopandas=1.0.0.dev
  - geopy=1.20.0
  - geotiff=1.5.1
  - geoviews=1.6.3
  - git=2.23.0
  - gitpython=3.0.3
  - google-cloud-container=0.3.0
  - google-cloud-storage=1.20.0
  - holoviews=1.12.5
  - icu=64.2
  - ipyleaflet=0.11.2
  - jedi=0.15.1
  - kubernetes=1.16.1
  - lz4=2.2.1
  - make=4.2.1
  - matplotlib=3.1.1
  - nb_conda_kernels=2.2.2
  - ncurses=6.1
  - netcdf-fortran=4.4.5
  - netcdf4=1.5.1.2
  - numba=0.45.1
  - numcodecs=0.6.3
  - pandas=0.25.1
  - pip=19.2.3
  - plotly=4.1.1
  - polyline=1.4.0
  - python=3.6
  - pyshp=2.1.0
  - python-blosc=1.8.1
  - python-snappy=0.5.4
  - pyviz_comms=0.7.2
  - PyYAML=5.1.2
  - rasterio=1.0.28
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - shapely=1.6.4
  - statsmodels=0.10.1
  - tini=0.18.0
  - uritemplate=3.0.0
  - xarray=0.13.0
  - xesmf=0.2.0
  - xlrd=1.2.0
  - zarr=2.3.2
  - zeromq=4.3.2
  - zict=1.0.0
  - pip:
    - mapbox==0.18.0
    - py-noaa==1.0
    - sidecar==0.3.0
    - climate-toolbox==0.1.5
    - impactlab-tools==0.3.1
    - parameterize_jobs==0.1.1
    - rhg_compute_tools==0.2.0
