name: base
channels:
  - conda-forge
  - conda-forge/label/dev
dependencies:
  - beautifulsoup4
  - boto3
  - bqplot
  - bumpversion
  - cachecontrol
  - cartopy
  - cftime
  - click
  - compilers
  - dask
  - dask-glm
  - dask-kubernetes
  - dask-ml
  - datashader
  - distributed
  - dropbox
  - esmpy
  - fastparquet
  - fiona=1.8.9.post2
  - fusepy
  - gcsfs
  - gdal=2.4.3
  - geoalchemy2
  - geopandas=1.0.0.dev
  - geopy
  - geotiff
  - geoviews
  - git
  - gitpython
  - google-cloud-container
  - google-cloud-storage
  - holoviews
  - h5netcdf
  - icu
  - ipyleaflet
  - jedi
  - kubernetes
  - lapack
  - lz4
  - make
  - matplotlib
  - nb_conda_kernels
  - nc-time-axis
  - ncurses
  - netcdf-fortran
  - netcdf4
  - numba
  - numcodecs
  - pandas
  - pip
  - plotly
  - polyline
  - pygeos
  - pyinterp
  - pyshp
  - python
  - python-blosc
  - python-snappy
  - pyviz_comms
  - PyYAML
  - rasterio=1.0.28
  - regionmask
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - sparse
  - statsmodels
  - tini
  - unzip
  - uritemplate
  - xarray
  - xesmf
  - xgcm
  - xhistogram
  - xlrd
  - xrft
  - zarr
  - zeromq
  - zict
  - pip:
    - mapbox
    - py-noaa
    - sidecar
    - climate-toolbox
    - impactlab-tools
    - parameterize_jobs
    - rhg_compute_tools
    - git+https://github.com/NCAR/intake-esm.git
