channels:
- conda-forge
dependencies:
- beautifulsoup4=4.9
- blas
- bottleneck=1.3
- boto3=1.13
- bqplot=0.12
- bump2version
- cachecontrol=0.12
- cartopy=0.17
- cftime=1.1
- click=7.1
- compilers=1.0
- dask=2.17
- dask-glm=0.2
- dask-kubernetes=0.10
- dask-ml=1.5
- datashader=0.11
- distributed=2.17
- dropbox=9.4
- esmpy=7.1
- fastparquet=0.4
- fiona=1.8
- gcsfs=0.6
- gdal=3.0
- geopandas=0.7
- geotiff=1.5
- geoviews=1.8
- git=2.26
- gitpython=3.1
- google-cloud-container=0.3
- google-cloud-storage=1.28
- holoviews=1.13
- h5netcdf=0.8
- intake-esm=2020.5
- jedi=0.17
- jupyter-server-proxy=1.5
- kubernetes=1.18
- lz4=3.0
- make=4.3
- matplotlib=3.1
- nc-time-axis=1.2
- netcdf-fortran=4.4
- netcdf4=1.5
- numba=0.48
- pandas=1.0
- phantomjs=2.1 # optional dependency of geoviews
- pillow  # optional dependency of geoviews
- pip=19.3
- plotly=4.8
- pyinterp=0.3
- pyshp=2.1
- python=3.7
- pyyaml=5.3
- rasterio=1.1
- regionmask=0.5
- rtree=0.9
- scikit-image=0.17
- scikit-learn=0.23
- scipy=1.4
- seaborn=0.10
- selenium=3.141 # optional dependency of geoviews
- shapely=1.7
- sparse=0.9
- statsmodels=0.11
- tini=0.18
- xarray=0.15
- xesmf=0.3
- xhistogram=0.1
- xlrd=1.2
- zarr=2.4
- zeromq=4.3
- pip:
  - py-noaa
  - sidecar
  - climate-toolbox
  - parameterize-jobs
  - rhg_compute_tools
name: base
