name: base
channels:
  - conda-forge
  - conda-forge/label/dev
dependencies:
  - beautifulsoup4=4.8.0
  - bokeh=1.3.4
  - boto3=1.9.243
  - bqplot=0.11.8
  - bumpversion=0.5.3
  - cachecontrol=0.12.5
  - cartopy=0.17.0
  - click=7.0
  - cloudpickle=1.2.2
  - cytoolz=0.10.0
  - dask=2.5.2
  - dask-glm=0.2.0
  - dask-kubernetes=0.9.2
  - dask-ml=1.0.0
  - datashader=0.7.0
  - distributed=2.5.2
  - esmpy=7.1.0
  - fastparquet=0.3.2
  - fiona=1.8.7
  - fusepy=3.0.1
  - gcsfs=0.3.1
  - gdal=2.4.2
  - geoalchemy2=0.6.3
  - geopandas=1.0.0.dev
  - geopy=1.20.0
  - geotiff=1.5.1
  - geoviews=1.6.3
  - git=2.23.0
  - gitpython=3.0.3
  - google-cloud-container=0.3.0
  - google-cloud-storage=1.20.0
  - holoviews=1.12.5
  - icu=64.2
  - ipyleaflet
  - jedi
  - kubernetes
  - lz4
  - make
  - matplotlib
  - nb_conda_kernels
  - ncurses
  - netcdf-fortran
  - netcdf4
  - numba
  - numcodecs
  - pandas
  - pip
  - plotly
  - polyline
  - python=3.6
  - pyshp
  - python-blosc
  - python-snappy
  - pyviz_comms
  - PyYAML
  - rasterio
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - tini
  - toolz
  - tornado
  - tox
  - tqdm
  - urllib3
  - uritemplate
  - wheel
  - xarray
  - xesmf
  - xlrd
  - zarr
  - zeromq
  - zict
  - pip:
    - mapbox
    - py-noaa
    - sidecar
    - rhg_compute_tools
    - impactlab-tools
    - climate-toolbox
    - parameterize_jobs
