name: base
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - bokeh
  - bqplot
  - bumpversion
  - cartopy
  - click
  - cloudpickle
  - cytoolz
  - dask
  - dask-glm
  - dask-kubernetes
  - dask-ml
  - datashader
  - distributed
  - esmf
  - esmpy
  - fastparquet
  - fiona
  - fusepy
  - gcsfs
  - gdal
  - geoalchemy2
  - geopy
  - geotiff
  - geoviews
  - git
  - gitpython
  - google-cloud-sdk
  - google-cloud-container
  - google-cloud-storage
  - holoviews
  - icu
  - ipdb
  - ipyleaflet
  - jedi
  - kubernetes
  - lz4
  - make
  - matplotlib
  - nb_conda_kernels
  - ncurses
  - netcdf-fortran
  - netcdf4
  - numba
  - numcodecs
  - pandas
  - pip
  - plotly
  - pyshp
  - python-blosc
  - python-snappy
  - pyviz_comms
  - PyYAML
  - rasterio
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - toolz
  - tornado
  - tox
  - tqdm
  - urllib3
  - wheel
  - xarray
  - xesmf
  - xlrd
  - zarr
  - zeromq
  - zict
  - pip:
    - mapbox
    - py-noaa
    - sidecar
    - rhg_compute_tools
    - impactlab-tools
    - climate-toolbox
    - parameterize_jobs
