name: spatial
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - bokeh=0.12.14
  - cytoolz
  - datashader
  - dask=0.17.2
  - gdal=2.2.4
  - esmpy
  - zarr
  - distributed=1.21.5
  - fastparquet
  - git
  - ipywidgets
  - jupyterlab
  - ipython
  - jupyter
  - holoviews
  - lz4=1.1.0
  - matplotlib
  - nb_conda_kernels
  - netcdf4
  - nomkl
  - numba=0.37.0
  - numcodecs
  - numpy=1.14.2
  - pandas
  - python-blosc=1.4.4
  - scipy
  - scikit-image
  - tornado
  - xarray=0.10.7
  - zict
  - rasterio
  - cartopy
  - conda-forge/label/dev::geopandas
  - pip:
    - wget
    - google-cloud==0.32.0
    - google-cloud-storage
    - gsutil
    - fusepy
    - click
    - jedi
    - kubernetes
    - pyasn1
    - click
    - urllib3
    - xesmf
    - daskernetes==0.1.3
    - git+https://github.com/dask/dask-kubernetes@5ba08f714ef38e585e9f2038b6be530c578b96dd
    - git+https://github.com/ioam/holoviews@3f015c0a531f54518abbfecffaac72a7b3554ed3
    - git+https://github.com/dask/gcsfs@2fbdc27e838a531ada080886ae778cb370ae48b8
    - git+https://github.com/jupyterhub/nbserverproxy
