singleuser:
  image:
    name: jgerardsimcock/notebook
    tag: 2018-03-09
  cmd: ['start-singleuser.sh']
    extraEnv:
      EXTRA_PIP_PACKAGES: >-
      GCSFUSE_BUCKET: jhub-rhg
  storage:
    extraVolumes:
      - name: fuse
        hostPath:
          path: /dev/fuse
    extraVolumeMounts:
      - name: fuse
        mountPath: /dev/fuse
  cpu:
    limit: 2
    guarantee: 1
  memory:
    limit: 4G
    guarantee: 2G

rbac:
  enabled: false

hub:
  extraConfig: |
    c.JupyterHub.log_level = 'DEBUG'
    c.KubeSpawner.singleuser_service_account = 'default'
    c.Spawner.default_url = '/lab'
    from kubernetes import client
    def modify_pod_hook(spawner, pod):
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
        )
        return pod
    c.KubeSpawner.modify_pod_hook = modify_pod_hook
  #   c.JupyterHub.logo_file = '/usr/local/share/jupyter/hub/static/custom/images/logo.png'
  #   c.JupyterHub.template_paths = ['/usr/local/share/jupyter/hub/custom_templates/',
  #                                  '/usr/local/share/jupyter/hub/templates/']

  # extraVolumes:
  #   - name: custom-templates
  #     gitRepo:
  #       repository: "https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git"
  #       revision: "5dbc3dca690a05ce499d9829e181d2c0bc107fb4"
  # extraVolumeMounts:
  #   - mountPath: /usr/local/share/jupyter/hub/custom_templates
  #     name: custom-templates
  #     subPath: "pangeo-custom-jupyterhub-templates/templates"
  #   - mountPath: /usr/local/share/jupyter/hub/static/custom
  #     name: custom-templates
  #     subPath: "pangeo-custom-jupyterhub-templates/assets"

  prePuller:
    hook:
      enabled: false

cull:
  enabled: true
  users: false
  timeout: 3600
  every: 600