jupyterhub:
  singleuser:
    image:
      name: rhodium/notebook
      tag: 2018-07-28.03
    storage:
      capacity: 10Gi
    dynamic:
      storageClass: jupyterhub-user-ssd
    serviceAccountName: daskkubernetes
    cmd: ['start-singleuser.sh']

    storage:
      extraVolumes:
        - name: fuse
          hostPath:
            path: /dev/fuse
      extraVolumeMounts:
        - name: fuse
          mountPath: /dev/fuse
    cloudMetadata:
      enabled: true

  hub:
    extraConfig: |
      from kubernetes import client
      def modify_pod_hook(spawner, pod):
          pod.spec.containers[0].security_context = client.V1SecurityContext(
              privileged=True,
              capabilities=client.V1Capabilities(
                  add=['SYS_ADMIN']
              )
          )
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod_hook
      c.Authenticator.whitelist = {"jgerardsimcock", 
                                    "delgadom", 
                                    "moonlimb", 
                                    "kemccusker",
                                    "hpitt",
                                    "wjherndon",
                                    "bolliger32", 
                                    "jaysayre",
                                    "}  


    
  cull:
    enabled: true
    users: false
    timeout: 1200
    every: 600 