# Only the packages necessary to build a dask-gateway scheduler. As seen here:
# https://github.com/dask/dask-gateway/blob/master/dask-gateway/Dockerfile
channels:
    - conda-forge
dependencies:
    - aiohttp=3.6.2=py38h516909a_0
    - dask=2.25.0=py_0
    - distributed=2.25.0=py38h32f6830_0
    - dask-gateway=0.8.0=py38h32f6830_0
    - numpy=1.19.1=py38hbc27379_2
    - pandas=1.1.1=py38h950e882_0
name: base
  