## using same base image as the "base image for the base image" of the notebook image
FROM ubuntu:focal-20201008@sha256:1d7b639619bdca2d008eca2d5293e3c43ff84cbee597ff76de3b7a7de3e84956
ARG DEBIAN_FRONTEND=noninteractive

# needed to properly install packages that use numpy libraries
ENV NPY_DISTUTILS_APPEND_FLAGS=1

# needed so that matplotlib will work headless
ENV MPLBACKEND=Agg

## filepath curation
COPY shared_resources /tempdir
COPY add_service_creds.py /usr/bin

# install apt-get packages
RUN apt-get update -y --no-install-recommends
RUN apt-get install -yq --no-install-recommends \
  ca-certificates \
  locales \
  sudo \
  wget

###########
## install miniconda (following jupyter/base-notebook
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen
    
ENV CONDA_DIR=/opt/conda \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8
ENV PATH=$CONDA_DIR/bin:$PATH

ENV MINICONDA_VERSION=4.8.3 \
    MINICONDA_MD5=d63adf39f2c220950a063e0529d4ff74 \
    CONDA_VERSION=4.8.3

WORKDIR /tmp
RUN wget --quiet https://repo.continuum.io/miniconda/Miniconda3-py38_${MINICONDA_VERSION}-Linux-x86_64.sh && \
    echo "${MINICONDA_MD5} *Miniconda3-py38_${MINICONDA_VERSION}-Linux-x86_64.sh" | md5sum -c - && \
    /bin/bash Miniconda3-py38_${MINICONDA_VERSION}-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-py38_${MINICONDA_VERSION}-Linux-x86_64.sh && \
    conda config --system --prepend channels conda-forge && \
    conda config --system --set channel_priority strict && \
    conda update -n base --yes conda && \
    conda update --all --yes && \
    conda install mamba
###########

## set up python env
RUN mkdir /opt/conda/specs
COPY shared_resources/scheduler_environment.yml /opt/conda/specs
COPY shared_resources/base_environment.yml /opt/conda/specs
RUN mamba env update -f /opt/conda/specs/scheduler_environment.yml

## clean up
RUN rm -rf /var/lib/apt/lists/* /tmp/*\
    && mamba clean -yaf \
    && sudo apt-get clean

WORKDIR /

# set entrypoint to same as default dask-gateway scheduler
ENTRYPOINT ["tini", "-g", "--"]